import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The ONE emit that lands outside dist/, because native build systems cannot import this
 * package. Both files are COMMITTED, not gitignored, and CI re-runs the generator to prove
 * they are fresh. See docs/13 UXG-26 for the decision.
 */
export function emitNativeSplashColour(resolved: Map<string, string>, repoRoot: string) {
  const canvas = resolved.get('canvas');
  if (!canvas || /^#[0-9a-fA-F]{6}$/.test(canvas) === false) {
    throw new Error(`--canvas must resolve to #RRGGBB for the native splash, got: ${canvas}`);
  }

  const mobileDir = join(repoRoot, 'apps', 'mobile');
  const banner = 'GENERATED by packages/tokens/build.ts from design/ds-source — DO NOT EDIT.';

  // Android: res/values/colors.xml, referenced by values/ and values-v31/ styles.
  const androidDir = join(mobileDir, 'android', 'app', 'src', 'main', 'res', 'values');
  mkdirSync(androidDir, { recursive: true });
  writeFileSync(
    join(androidDir, 'colors.xml'),
    `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${banner} -->\n<resources>\n    <color name="splash_canvas">${canvas.toUpperCase()}</color>\n</resources>\n`,
  );

  // iOS: a named colour in the asset catalog. Asset catalogs are folder references, so a new
  // .colorset compiles without touching project.pbxproj. Components are the hex split — the
  // catalog format has no plain hex field.
  const colorsetDir = join(
    mobileDir,
    'ios',
    'HelioGridMobile',
    'Images.xcassets',
    'SplashCanvas.colorset',
  );
  mkdirSync(colorsetDir, { recursive: true });
  const [r, g, b] = [1, 3, 5].map((i) => `0x${canvas.slice(i, i + 2).toUpperCase()}`);
  writeFileSync(
    join(colorsetDir, 'Contents.json'),
    `${JSON.stringify(
      {
        $comment: banner,
        colors: [
          {
            color: {
              'color-space': 'srgb',
              components: { alpha: '1.000', blue: b, green: g, red: r },
            },
            idiom: 'universal',
          },
        ],
        info: { author: 'xcode', version: 1 },
      },
      null,
      2,
    )}\n`,
  );
}
