/**
 * Mint an RS256 JWT for one Temporal identity. DEVELOPMENT ONLY — the signing key lives in
 * `infra/temporal/pki/jwt/`, which is gitignored and regenerated by `make-dev-pki.sh`.
 *
 *   node scripts/mint-token.mjs api|worker|operator|reader [ttlSeconds]
 *
 * The `permissions` claim is what Temporal's DEFAULT authorizer reads. Its vocabulary is
 * `<namespace>:<role>` with role in {read, write, worker, admin}, plus the reserved
 * `temporal-system:admin` for cluster-level operations. Least privilege here means:
 *
 *   api       heliogrid:write   — start and signal workflows; may NOT poll a task queue
 *   worker    heliogrid:write   — poll and complete tasks. The SAME role as api, and that
 *                               is a finding, not a shortcut: see the measurement below.
 *   operator  temporal-system:admin — cluster administration, used by a human, never a service
 *   reader    heliogrid:read    — exists ONLY to prove that a valid certificate plus an
 *                                insufficient token is refused. Certificate authentication
 *                                is not authorization, and this is how that is demonstrated
 *                                rather than asserted.
 */
import { createSign } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKI = join(dirname(fileURLToPath(import.meta.url)), '..', 'pki');
const KEY_ID = 'heliogrid-dev';
const NAMESPACE = 'heliogrid';

const PERMISSIONS = {
  api: [`${NAMESPACE}:write`],
  // MEASURED, not assumed (2026-08-25, SDK 1.22.0 / server 1.30.6). A worker needs
  // `namespace:write`, and the results were:
  //     worker              → never starts: DescribeNamespace is refused and the SDK reports
  //                           "Namespace heliogrid was not found or otherwise could not be
  //                           described", which reads as a missing namespace, not a missing
  //                           permission
  //     worker + read       → starts, looks healthy for 60 seconds, then the FIRST long poll
  //                           returns PermissionDenied and the worker goes to state FAILED.
  //                           A 14-second smoke test calls this green — it is not
  //     write               → polls, executes, completes
  //
  // So `worker` is neither sufficient nor necessary, and the built-in authorizer CANNOT
  // separate "may start workflows" from "may poll a task queue": both are namespace:write.
  // The api and worker identities therefore differ by CERTIFICATE and by token subject, not
  // by privilege. Splitting them for real needs a custom Authorizer plugin or a private
  // enforcing proxy filtering by gRPC method — a Track 8 decision, recorded in README §5.
  worker: [`${NAMESPACE}:write`],
  operator: ['temporal-system:admin'],
  reader: [`${NAMESPACE}:read`],
};

const identity = process.argv[2];
const ttl = Number(process.argv[3] ?? 3600);
const permissions = PERMISSIONS[identity];
if (!permissions) {
  process.stderr.write(`unknown identity ${identity}; expected ${Object.keys(PERMISSIONS)}\n`);
  process.exit(2);
}

const b64 = (obj) => Buffer.from(JSON.stringify(obj)).toString('base64url');
const now = Math.floor(Date.now() / 1000);
const header = b64({ alg: 'RS256', typ: 'JWT', kid: KEY_ID });
const payload = b64({
  sub: identity,
  iat: now,
  exp: now + ttl,
  permissions,
});
const signature = createSign('RSA-SHA256')
  .update(`${header}.${payload}`)
  .sign(readFileSync(join(PKI, 'jwt', 'private.pem')), 'base64url');

process.stdout.write(`Bearer ${header}.${payload}.${signature}`);
