import UIKit
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider

@main
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?

  var reactNativeDelegate: ReactNativeDelegate?
  var reactNativeFactory: RCTReactNativeFactory?

  func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    let delegate = ReactNativeDelegate()
    let factory = RCTReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory

    window = UIWindow(frame: UIScreen.main.bounds)

    factory.startReactNative(
      withModuleName: "HelioGridMobile",
      in: window,
      launchOptions: launchOptions
    )

    // Close the seam between the launch screen and JS's first frame.
    //
    // The storyboard is torn down as soon as the window is shown, but React Native's root
    // view stays blank until the JS bundle renders — and it defaults to WHITE, which flashes
    // against the canvas either side of it. Painting both surfaces the same canvas means
    // there is no white surface at any point in the launch, rather than a flash too short to
    // argue about.
    //
    // Same NAMED asset the storyboard uses, generated by packages/tokens/build.ts — no hex
    // is transcribed here (docs/13 UXG-26).
    let splashCanvas = UIColor(named: "SplashCanvas")
    window?.backgroundColor = splashCanvas
    window?.rootViewController?.view.backgroundColor = splashCanvas

    return true
  }
}

class ReactNativeDelegate: RCTDefaultReactNativeFactoryDelegate {
  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}
